import { Language } from './types';

export const translations = {
  en: {
    appName: "KisanDost",
    tagline: "Your AI Plant Doctor",
    login: "Login",
    register: "Register",
    name: "Full Name",
    email: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account? Register",
    hasAccount: "Already have an account? Login",
    detect: "Detect Disease",
    history: "History",
    settings: "Settings",
    logout: "Logout",
    uploadImage: "Upload or Take Photo",
    analyzing: "Analyzing plant...",
    healthy: "Plant is healthy",
    diseased: "Disease Detected",
    crop: "Crop",
    disease: "Disease",
    confidence: "Confidence",
    symptoms: "Symptoms",
    organic: "Organic Treatment",
    chemical: "Chemical Treatment",
    prevention: "Prevention Tips",
    care: "Care Tips",
    safetyWarning: "SAFETY WARNING",
    safetyTips: [
      "Wear gloves while handling chemicals",
      "Wear a mask to avoid breathing chemicals",
      "Keep chemicals away from children",
      "Wash hands thoroughly after use"
    ],
    unclear: "Image is not clear. Please take photo in daylight.",
    noHistory: "No scans yet. Start by checking a plant!",
    back: "Back"
  },
  hi: {
    appName: "किसानदोस्त",
    tagline: "आपका AI प्लांट डॉक्टर",
    login: "लॉगिन",
    register: "रजिस्टर",
    name: "पूरा नाम",
    email: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    noAccount: "खाता नहीं है? रजिस्टर करें",
    hasAccount: "पहले से खाता है? लॉगिन करें",
    detect: "बीमारी पहचानें",
    history: "इतिहास",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    uploadImage: "फोटो अपलोड करें या लें",
    analyzing: "पौधे की जांच हो रही है...",
    healthy: "पौधा स्वस्थ है",
    diseased: "बीमारी का पता चला",
    crop: "फसल",
    disease: "बीमारी",
    confidence: "विश्वास",
    symptoms: "लक्षण",
    organic: "जैविक उपचार",
    chemical: "रासायनिक उपचार",
    prevention: "बचाव के टिप्स",
    care: "देखभाल के टिप्स",
    safetyWarning: "सुरक्षा चेतावनी",
    safetyTips: [
      "रसायनों का उपयोग करते समय दस्ताने पहनें",
      "सांस के जरिए रसायनों से बचने के लिए मास्क पहनें",
      "रसायनों को बच्चों से दूर रखें",
      "उपयोग के बाद हाथ अच्छी तरह धोएं"
    ],
    unclear: "फोटो साफ नहीं है। कृपया दिन की रोशनी में फोटो लें।",
    noHistory: "अभी तक कोई स्कैन नहीं। पौधे की जांच से शुरू करें!",
    back: "पीछे"
  },
  te: {
    appName: "కిసాన్ దోస్త్",
    tagline: "మీ AI ప్లాంట్ డాక్టర్",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    name: "పూర్తి పేరు",
    email: "ఈమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    noAccount: "ఖాతా లేదా? రిజిస్టర్ అవ్వండి",
    hasAccount: "ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి",
    detect: "వ్యాధిని గుర్తించండి",
    history: "చరిత్ర",
    settings: "సెట్టింగ్‌లు",
    logout: "లాగౌట్",
    uploadImage: "ఫోటో అప్‌లోడ్ చేయండి లేదా తీయండి",
    analyzing: "మొక్కను పరిశీలిస్తోంది...",
    healthy: "మొక్క ఆరోగ్యంగా ఉంది",
    diseased: "వ్యాధి గుర్తించబడింది",
    crop: "పంట",
    disease: "వ్యాధి",
    confidence: "నమ్మకం",
    symptoms: "లక్షణాలు",
    organic: "సేంద్రియ చికిత్స",
    chemical: "రసాయన చికిత్స",
    prevention: "నివారణ చిట్కాలు",
    care: "సంరక్షణ చిట్కాలు",
    safetyWarning: "భద్రతా హెచ్చరిక",
    safetyTips: [
      "రసాయనాలను వాడేటప్పుడు గ్లౌజులు ధరించండి",
      "రసాయనాలు పీల్చకుండా మాస్క్ ధరించండి",
      "రసాయనాలను పిల్లలకు దూరంగా ఉంచండి",
      "వాడిన తర్వాత చేతులను శుభ్రంగా కడుక్కోండి"
    ],
    unclear: "చిత్రం స్పష్టంగా లేదు. దయచేసి పగటి వెలుతురులో ఫోటో తీయండి.",
    noHistory: "ఇంకా స్కాన్‌లు లేవు. మొక్కను తనిఖీ చేయడం ద్వారా ప్రారంభించండి!",
    back: "వెనుకకు"
  },
  ta: {
    appName: "கிசான் தோஸ்த்",
    tagline: "உங்கள் AI தாவர மருத்துவர்",
    login: "உள்நுழை",
    register: "பதிவு செய்",
    name: "முழு பெயர்",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல்லை மறந்தீர்களா?",
    noAccount: "கணக்கு இல்லையா? பதிவு செய்",
    hasAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழை",
    detect: "நோயைக் கண்டறி",
    history: "வரலாறு",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    uploadImage: "புகைப்படத்தைப் பதிவேற்றவும் அல்லது எடுக்கவும்",
    analyzing: "தாவரத்தை ஆய்வு செய்கிறது...",
    healthy: "தாவரம் ஆரோக்கியமாக உள்ளது",
    diseased: "நோய் கண்டறியப்பட்டது",
    crop: "பயிர்",
    disease: "நோய்",
    confidence: "நம்பிக்கை",
    symptoms: "அறிகுறிகள்",
    organic: "இயற்கை சிகிச்சை",
    chemical: "ரசாயன சிகிச்சை",
    prevention: "தடுப்பு குறிப்புகள்",
    care: "பராமரிப்பு குறிப்புகள்",
    safetyWarning: "பாதுகாப்பு எச்சரிக்கை",
    safetyTips: [
      "ரசாயனங்களைக் கையாளும் போது கையுறைகளை அணியுங்கள்",
      "ரசாயனங்களை சுவாசிப்பதைத் தவிர்க்க முகமூடி அணியுங்கள்",
      "ரசாயனங்களை குழந்தைகளுக்கு எட்டாதவாறு வைத்திருங்கள்",
      "பயன்பாட்டிற்குப் பிறகு கைகளை நன்றாகக் கழுவுங்கள்"
    ],
    unclear: "படம் தெளிவாக இல்லை. பகல் வெளிச்சத்தில் புகைப்படம் எடுக்கவும்.",
    noHistory: "இன்னும் ஸ்கேன்கள் இல்லை. ஒரு தாவரத்தைச் சரிபார்ப்பதன் மூலம் தொடங்கவும்!",
    back: "பின்னால்"
  }
};
